"""Generates synthetic oil and gas knowledge base entries."""

from typing import List, Dict


def generate_knowledge_base() -> List[Dict]:
    """Generate comprehensive oil and gas knowledge base with 50+ topics."""
    documents = []

    drilling_docs = [
        {"title": "Rotary Drilling Fundamentals", "category": "Drilling",
         "content": "Rotary drilling is the most common method used to drill oil and gas wells. The process involves rotating a drill bit at the bottom of the hole while drilling fluid (mud) is pumped down through the drill string to cool the bit and carry cuttings to the surface. The rotary table or top drive provides the rotational force. Typical penetration rates range from 10 to 50 feet per hour depending on formation hardness. The weight on bit (WOB) is controlled by the number of drill collars in the bottom hole assembly. A standard BHA includes drill collars, stabilizers, and the drill bit.",
         "source": "SPE Drilling Engineering Manual"},
        {"title": "Drilling Fluid Properties and Management", "category": "Drilling",
         "content": "Drilling fluid, commonly called drilling mud, serves multiple critical functions: cooling and lubricating the drill bit, carrying cuttings to the surface, maintaining hydrostatic pressure to prevent formation fluids from entering the wellbore, and suspending cuttings when circulation stops. Key properties include density (measured in ppg or sg), viscosity (measured with Marsh funnel), filter loss (API and HTHP), pH level (typically 8.5-11.0), and sand content. Water-based muds (WBM) are most common, with typical densities from 8.5 to 18 ppg. Oil-based muds (OBM) are used for challenging wells with high temperature or reactive shales. Mud weight must be sufficient to maintain primary well control while not fracturing weak formations.",
         "source": "API RP 13D"},
        {"title": "Wellbore Stability and Hole Cleaning", "category": "Drilling",
         "content": "Wellbore stability is critical for successful drilling operations. Instability manifests as borehole breakouts, washouts, or tight holes. The mud weight window is defined by the collapse pressure on the lower bound and the fracture gradient on the upper bound. Tripping pipe must be done at appropriate speeds to avoid surge and swab pressures. Hole cleaning efficiency depends on flow rate, pipe rotation, and mud rheology. Minimum annular velocity for adequate hole cleaning in deviated wells is typically 100-150 ft/min. In horizontal wells, cuttings beds can form on the low side if flow rate is insufficient. Periodic wiper trips help maintain hole condition.",
         "source": "IADC Well Control Manual"},
        {"title": "Directional Drilling and Well Planning", "category": "Drilling",
         "content": "Directional drilling involves controlling the wellbore trajectory to reach targets that are not directly below the surface location. Key terms include build rate (measured in degrees per 100 feet), dogleg severity, inclination (angle from vertical), and azimuth (compass direction). Measurement while drilling (MWD) tools provide real-time survey data. Logging while drilling (LWD) adds formation evaluation capability. Rotary steerable systems (RSS) allow continuous steering while rotating the entire drill string. Common well profiles include build-and-hold, S-shaped, and horizontal. Build rates typically range from 2 to 8 degrees per 100 feet.",
         "source": "SPE Drilling Monograph"},
        {"title": "Casing Design and Cementing", "category": "Drilling",
         "content": "Casing strings are installed to maintain wellbore integrity. A typical well has surface casing (20-36 inches), intermediate casing (13-3/8 to 16 inches), and production casing (5-1/2 to 9-5/8 inches). Casing is sized based on well depth, formation pressures, and production requirements. API 5CT specifies casing grades from H40 to Q125 with yield strengths from 40,000 to 125,000 psi. Cementing involves pumping cement slurry into the annulus between casing and wellbore. Primary cement jobs must achieve adequate top of cement (TOC) and zonal isolation. Cement density typically ranges from 11 to 17 ppg depending on formation pressures.",
         "source": "API Bulletin 5C2"},
        {"title": "Blowout Prevention and Well Control", "category": "Drilling",
         "content": "Well control is the management of formation pressures to prevent unplanned release of fluids (kicks). A kick occurs when formation pressure exceeds hydrostatic pressure of the mud column. Blowout preventers (BOPs) are installed at the wellhead to provide mechanical barriers. A typical BOP stack includes annular preventers and pipe rams capable of closing around tubulars. Kick detection methods include monitoring pit volumes, flow rates, and hookload. If a kick is detected, the well is shut in using the BOP, and kill operations (wait and weight or driller method) are performed. Maximum allowable surface pressure (MASP) is calculated based on the weakest exposed formation.",
         "source": "API Standard 53"},
        {"title": "Drill Bit Selection and Optimization", "category": "Drilling",
         "content": "Drill bit selection is based on formation type, depth, and drilling objectives. Tricone roller cone bits are used for hard formations with IADC codes from 1-1-1 to 8-3-7. Polycrystalline diamond compact (PDC) bits are preferred for soft to medium formations with higher rates of penetration. Fixed cutter bits have no moving parts and can drill longer intervals. Specific energy analysis helps optimize WOB and RPM. Mechanical specific energy (MSE) calculations identify inefficient drilling. Optimal WOB for PDC bits typically ranges from 2 to 6 klbs per inch of bit diameter. Bit records should track ROP, WOB, RPM, torque, and hydraulic parameters.",
         "source": "SPE Drilling Engineering"},
        {"title": "Well Abandonment Procedures", "category": "Drilling",
         "content": "Well abandonment (plugging and abandonment, PA) requires proper isolation of all hydrocarbon zones. Regulatory agencies require cement plugs at specific intervals to prevent fluid migration between zones. Common plug locations include below the deepest hydrocarbon zone, at each productive interval, above the shallowest hydrocarbon zone, and at surface. Bridge plugs or cement plugs are set to provide mechanical barriers. Casing may be cut and pulled above surface or below a specified depth. All PA operations must be documented with location surveys and cement bond logs as required by regulatory authorities.",
         "source": "NORSOK D-010"},
    ]

    safety_docs = [
        {"title": "Personal Protective Equipment Requirements", "category": "Safety",
         "content": "All personnel on oil and gas facilities must wear appropriate PPE at all times. Mandatory PPE includes hard hat, safety glasses, steel-toed boots, hearing protection in designated areas, and fire-resistant clothing (FRC) when exposed to hydrocarbons. Additional PPE may include chemical-resistant gloves, fall protection harness, face shields, and respiratory protection. PPE must meet ANSI/ISEA standards. Hard hats must be replaced after any impact or every 5 years. Safety glasses must have ANSI Z87.1 rating. Boots must have ASTM F2413 impact and compression resistance. Fire-resistant clothing must meet NFPA 2112 standards.",
         "source": "OSHA 29 CFR 1910.132"},
        {"title": "Hot Work Permits and Fire Prevention", "category": "Safety",
         "content": "Hot work includes welding, cutting, grinding, and any operation producing sparks or flames. A hot work permit is required before commencing any hot work on or near hydrocarbon processing areas. The permit must be issued by the site safety authority after gas testing confirms the atmosphere is within safe limits (less than 10% of LEL). Fire watch personnel must be posted during and 30 minutes after hot work completion. A minimum 35-foot exclusion zone must be established around hot work areas. Portable fire extinguishers must be within 25 feet of the work area. Gas testing must be repeated every 4 hours or whenever conditions change.",
         "source": "API RP 2009"},
        {"title": "Confined Space Entry Procedures", "category": "Safety",
         "content": "Confined spaces on oil and gas facilities include vessels, tanks, pits, pipelines, and manholes. Entry requires a permit signed by the entry supervisor. Before entry, atmospheric testing must confirm oxygen levels between 19.5% and 23.5%, flammable gases below 10% LEL, and toxic gases below permissible exposure limits. Ventilation must be maintained during entry. An attendant must be posted at the entrance at all times. Rescue equipment and trained rescue personnel must be available. Communication between entrant and attendant must be maintained continuously. Entry permits must include atmospheric test results, rescue procedures, and authorization signatures.",
         "source": "OSHA 29 CFR 1910.146"},
        {"title": "Hazardous Area Classification and Electrical Safety", "category": "Safety",
         "content": "Hazardous areas are classified according to API 500 and IEC 60079 based on the likelihood of flammable gases being present. Class I, Division 1 areas have ignitable concentrations under normal operation. Division 2 areas have ignitable concentrations only under abnormal conditions. Zone 0, 1, and 2 classifications follow IEC standards. Electrical equipment in classified areas must be rated for the specific hazard class and group. Common gas groups include Group IIA (propane), Group IIB (ethylene), and Group IIC (hydrogen). Inspection and maintenance of electrical equipment in hazardous areas must follow documented procedures.",
         "source": "API RP 500"},
        {"title": "Process Safety Management", "category": "Safety",
         "content": "Process Safety Management (PSM) under OSHA 29 CFR 1910.119 applies to processes involving highly hazardous chemicals above threshold quantities. The 14 elements of PSM include process information, hazard analysis, operating procedures, training, mechanical integrity, management of change, pre-startup safety review, hot work permits, incident investigation, emergency planning, compliance audits, trade secrets, employee participation, and contractor safety. The goal is to prevent catastrophic releases of toxic, reactive, flammable, or explosive chemicals. PSM covers the entire lifecycle from design through operation and decommissioning.",
         "source": "OSHA 29 CFR 1910.119"},
        {"title": "Fall Protection in Oil and Gas Operations", "category": "Safety",
         "content": "Fall protection is required whenever personnel work at heights above 6 feet (OSHA requirement). On drilling rigs and production platforms, fall protection includes guardrails, personal fall arrest systems (PFAS), safety nets, and restraint systems. Full body harnesses must comply with ANSI Z359.11 and be inspected before each use. Lanyards must have energy absorbers for heights over 6 feet. Self-retracting lifelines (SRLs) are preferred for vertical climbing. Anchor points must support 5,000 pounds or be designed with a 2:1 safety factor. Fall protection plans must be developed for non-routine work at heights.",
         "source": "API RP 54"},
    ]

    equipment_docs = [
        {"title": "Centrifugal Pump Selection and Sizing", "category": "Equipment",
         "content": "Centrifugal pumps are the most common type used in oil and gas operations. Pump selection depends on flow rate, total dynamic head (TDH), fluid properties, and system requirements. The affinity laws relate speed, flow, head, and power: Q1/Q2 = N1/N2, H1/H2 = (N1/N2)^2, P1/P2 = (N1/N2)^3. Net positive suction head required (NPSHr) must be less than NPSHa to avoid cavitation. Specific speed (Ns = N*Q^0.5/H^0.75) determines the best impeller type: radial (Ns < 1500), mixed flow (1500 < Ns < 4000), or axial (Ns > 4000). Hydraulic efficiency typically ranges from 60% to 85%. Pump curves show the relationship between head, flow, and efficiency at various speeds.",
         "source": "HI Pump Handbook"},
        {"title": "Heat Exchanger Design and Maintenance", "category": "Equipment",
         "content": "Shell and tube heat exchangers are the most common type in oil and gas processing. Design follows TEMA standards (R, C, or B service). The overall heat transfer coefficient (U) depends on fluid properties, flow geometry, and fouling factors. LMTD method calculates heat duty: Q = U * A * F * LMTD. Fouling reduces heat transfer efficiency over time. Mechanical cleaning is required when thermal performance drops below design values. Baffle spacing typically ranges from 20% to 100% of shell diameter. Vibration analysis is critical for tube bundles to prevent flow-induced vibration damage. Typical design pressures range from 150 to 3000 psig.",
         "source": "TEMA Standards 10th Edition"},
        {"title": "Compressor Operations and Maintenance", "category": "Equipment",
         "content": "Reciprocating and centrifugal compressors are used for gas compression in production and pipeline operations. Reciprocating compressors handle higher pressure ratios (up to 4:1 per stage) with lower flow rates. Centrifugal compressors provide high flow rates at moderate pressure ratios (1.5:1 to 3:1 per stage). Polytropic efficiency typically ranges from 75% to 85%. Surge is a critical operating limit for centrifugal compressors - anti-surge control systems prevent operation in the surge region. Intercooling between stages reduces discharge temperature and improves efficiency. Vibration monitoring and oil analysis are key predictive maintenance tools.",
         "source": "API 618 / API 617"},
        {"title": "Pressure Vessel Design and Inspection", "category": "Equipment",
         "content": "Pressure vessels are designed according to ASME BPVC Section VIII. The minimum wall thickness for a cylindrical shell under internal pressure is t = PR/(SE - 0.6P) where P is design pressure, R is inside radius, S is allowable stress, and E is joint efficiency. Vessels are categorized by MAWP: Class 1 (greater than 15 psig), Class 2 (between 15 and 300 psig), and Class 3 (greater than 300 psig). Inspection intervals follow API 510: external inspection annually, internal inspection every 5-10 years based on corrosion rate. Non-destructive examination (NDE) methods include UT, RT, MT, and PT. Hydrostatic testing at 1.5x MAWP is required for new vessels.",
         "source": "ASME BPVC Section VIII"},
        {"title": "Electric Submersible Pump Systems", "category": "Equipment",
         "content": "Electric submersible pumps (ESPs) are used for artificial lift in high-volume wells. A complete ESP system includes downhole motor, seal/protector, gas separator (optional), pump intake, multi-stage centrifugal pump, power cable, surface transformer, and variable speed drive (VSD). Pump stages are selected based on required total dynamic head and flow rate. Motor sizing accounts for fluid properties, well depth, and production rate. Operating temperature rating of the motor must exceed the bottomhole temperature. Typical ESP installations produce 200 to 80,000 bbl/day. Run life averages 2-5 years depending on operating conditions. Gas handling is critical - gas volume fraction above 10% can cause gas locking.",
         "source": "API RP 11S"},
        {"title": "Rod Pumping Systems", "category": "Equipment",
         "content": "Sucker rod pumping is the most common artificial lift method worldwide. The system consists of a surface pumping unit (beam pump), sucker rod string, and downhole pump (plunger and barrel). API RP 11L provides design methods for rod pump installations. Key design parameters include stroke length, strokes per minute, rod size, and pump depth. Polished rod load analysis uses the wave equation to determine downhole card shape. Typical beam pump units range from API 9-3 to API 1192. Optimization involves matching pump fillage, counterbalance, and motor loading. Gas interference and fluid pound are common operational problems.",
         "source": "API RP 11L"},
        {"title": "Pipeline Design and Integrity Management", "category": "Equipment",
         "content": "Oil and gas pipelines are designed according to API 5L for line pipe and ASME B31.4 (liquid) or B31.8 (gas). Wall thickness is calculated as t = PD/(2SE*F*T) where P is design pressure, D is outside diameter, S is specified minimum yield strength (SMYS), E is longitudinal joint factor, F is design factor (0.72 for class 1, 0.60 for class 2-4), and T is temperature derating factor. Internal corrosion is managed through chemical injection, internal coatings, and pigging operations. External corrosion protection uses cathodic protection (CP) with impressed current or sacrificial anodes. Integrity management follows API 1160 for liquids and ASME B31.8S for gas.",
         "source": "API 5L / ASME B31.8"},
    ]

    production_docs = [
        {"title": "Primary Recovery Mechanisms", "category": "Production",
         "content": "Primary recovery utilizes natural reservoir energy to produce hydrocarbons. The main mechanisms are solution gas drive, gas cap drive, water drive, gravity drainage, and combination drive. Solution gas drive reservoirs produce by gas liberation from oil as pressure drops below bubble point. Recovery factors typically range from 5% to 25%. Gas cap drive reservoirs benefit from expansion of the gas cap providing pressure support. Water drive reservoirs have natural water influx maintaining pressure. Recovery factors for strong water drive can reach 50-70%. Gravity drainage occurs in high-porosity, high-permeability formations with significant dip angles. Decline curve analysis helps predict future production rates and ultimate recovery.",
         "source": "SPE Petroleum Engineering Handbook"},
        {"title": "Enhanced Oil Recovery Methods", "category": "Production",
         "content": "EOR methods are employed after primary and secondary recovery to extract additional hydrocarbons. Thermal methods include steam flooding, cyclic steam stimulation (CSS), and in-situ combustion. Steam flooding reduces oil viscosity by heating the reservoir. Chemical EOR includes polymer flooding (improves sweep efficiency), surfactant flooding (reduces interfacial tension), and alkaline flooding. Miscible gas injection uses CO2 or hydrocarbon gases that miscible with reservoir oil. CO2-EOR can recover an additional 8-15% of original oil in place (OOIP). Immiscible gas injection provides pressure support without achieving miscibility. Each method requires careful screening of reservoir properties for economic viability.",
         "source": "DOE EOR Guidelines"},
        {"title": "Well Testing and Performance Analysis", "category": "Production",
         "content": "Well tests provide critical reservoir information including permeability, skin factor, and reservoir boundaries. Types of well tests include buildup tests, drawdown tests, interference tests, and step-rate tests. Pressure transient analysis uses log-log and semi-log plots to identify flow regimes: wellbore storage, radial flow, and boundary effects. Horner analysis for buildup tests plots pressure vs. Horner time to determine permeability-thickness (kh) and skin. Type curve matching provides estimates of reservoir parameters. Rate transient analysis extends well test concepts to long-term production data. Deliverability testing for gas wells includes isochronal and modified isochronal tests.",
         "source": "SPE Monograph Vol. 5"},
        {"title": "Production Chemistry and Flow Assurance", "category": "Production",
         "content": "Flow assurance ensures hydrocarbons flow from reservoir to processing facilities without disruption. Key issues include wax deposition, asphaltene precipitation, scale formation, gas hydrates, and emulsion formation. Wax (paraffin) deposits when temperature drops below the cloud point (typically 40-70 degrees C for waxy crudes). Asphaltenes precipitate due to pressure changes or incompatible fluids. Scale types include calcium carbonate (CaCO3), barium sulfate (BaSO4), and iron sulfide (FeS). Gas hydrates form at high pressure and low temperature conditions. Chemical inhibitors and mechanical methods (pigging, heating) are used to manage flow assurance challenges.",
         "source": "SPE Production Handbook"},
        {"title": "Artificial Lift Selection and Optimization", "category": "Production",
         "content": "Artificial lift is required when reservoir pressure is insufficient to produce at economic rates. Selection criteria include production rate, well depth, fluid properties, and operating environment. Rod pumping (beam units) is suitable for rates up to 1,500 bbl/day and depths to 10,000 ft. ESP systems handle high rates (200-80,000 bbl/day) at depths up to 15,000 ft. Gas lift uses injected gas to reduce fluid column weight and is flexible for varying production rates. Progressive cavity pumps (PCP) handle viscous fluids and solids-laden production. Hydraulic pumping uses high-pressure power fluid. Selection optimization considers artificial lift performance curves, nodal analysis, and economic evaluation.",
         "source": "Artificial Lift Handbook"},
        {"title": "Gas Processing and Treatment", "category": "Production",
         "content": "Raw natural gas requires processing to meet pipeline specifications. Key processes include dehydration (removing water vapor to less than 7 lb/MMSCF), sweetening (removing H2S and CO2), NGL extraction (recovering natural gas liquids), and sulfur recovery. Glycol dehydration uses triethylene glycol (TEG) with typical dew point depressions of 50-100 degrees F. Amine treating uses MEA, DEA, or MDEA solutions to remove acid gases. The Claus process converts H2S to elemental sulfur with recovery rates exceeding 99%. Gas sweetening specifications typically require H2S less than 4 ppm and CO2 less than 2%. Refrigeration and turboexpander processes recover NGLs for separate sale.",
         "source": "GPSA Engineering Data Book"},
        {"title": "Reservoir Characterization and Petrophysics", "category": "Production",
         "content": "Reservoir characterization integrates geological, geophysical, and petrophysical data to describe reservoir properties. Key parameters include porosity (typically 5-30%), permeability (0.1-10,000 mD), water saturation (Sw), and net-to-gross ratio. Porosity is determined from core analysis, well logs, and seismic data. Permeability from core analysis uses Darcy law: k = (Q * mu * L) / (A * delta_P). Water saturation is calculated from resistivity logs using Archie equation: Sw = (a * Rw / (phi^m * Rt))^(1/n). Special core analysis provides relative permeability, capillary pressure, and wettability data for reservoir simulation.",
         "source": "SPE Petrophysics Handbook"},
        {"title": "Workover and Well Intervention Operations", "category": "Production",
         "content": "Workover operations restore or enhance well productivity. Common workover reasons include mechanical failure, formation damage, water shutoff, and recompletion. Coiled tubing (CT) units provide rigless intervention capability for cleanouts, logging, and treatments. Wireline operations include slickline (mechanical operations) and electric line (logging and perforating). Snubbing units handle live well interventions under pressure. Stimulation treatments include hydraulic fracturing and acidizing. Fracturing creates fractures in the formation using high-pressure fluid with proppant (sand or ceramic). Matrix acidizing dissolves formation damage near the wellbore using HCl for carbonates or mud acid for sandstones.",
         "source": "IADC Workover Manual"},
    ]

    reservoir_docs = [
        {"title": "Reservoir Engineering Fundamentals", "category": "Reservoir",
         "content": "Reservoir engineering applies scientific principles to optimize hydrocarbon recovery. Material balance equations (MBE) relate production to reservoir pressure decline and fluid expansion. The general MBE accounts for oil expansion, dissolved gas release, gas cap expansion, and water influx. Darcy law governs fluid flow through porous media: q = -kA(mu)(dP/dx). Pseudo-steady state flow occurs during boundary-dominated production. Inflow performance relationship (IPR) curves show the relationship between flowing bottomhole pressure and production rate. Vogel IPR equation for solution gas drive reservoirs is q/qmax = 1 - 0.2(Pwf/Pr) - 0.8(Pwf/Pr)^2.",
         "source": "SPE Reservoir Engineering Handbook"},
        {"title": "Multiphase Flow in Pipes", "category": "Reservoir",
         "content": "Multiphase flow in production tubing and surface pipelines involves complex interactions between gas, oil, and water phases. Flow regimes include bubble, slug, churn, and annular flow. Pressure gradient calculations account for friction, gravity, and acceleration components. The Beggs and Brill correlation is widely used for multiphase pressure drop calculations. Holdup refers to the fraction of pipe cross-section occupied by the liquid phase. Liquid loading in gas wells occurs when gas velocity falls below the critical velocity needed to lift liquids. Multiphase flow meters measure individual phase flow rates using technologies such as venturi, Coriolis, and conductance probes.",
         "source": "SPE Production Operations"},
        {"title": "Stimulation Design and Optimization", "category": "Reservoir",
         "content": "Hydraulic fracturing creates conductive pathways from the wellbore into the reservoir. Treatment design specifies pump rate, fluid volume, proppant concentration, and proppant type. Typical pump rates range from 20 to 100 bbl/min. Proppant sizes range from 20/40 to 100 mesh sand or ceramic. Fracture half-length targets range from 200 to 2,000 ft. Acid fracturing uses HCl to etch conductive channels in carbonate formations. Matrix acidizing in sandstones uses 12-15% HCl with 3% HF (mud acid) to dissolve formation damage. Diversion techniques ensure uniform treatment distribution across multiple zones. Post-frac production analysis uses decline curve and pressure transient methods.",
         "source": "SPE Hydraulic Fracturing Handbook"},
        {"title": "Formation Damage Mechanisms", "category": "Reservoir",
         "content": "Formation damage reduces well productivity by impairing near-wellbore permeability. Damage mechanisms include: fines migration (movement of fine particles blocking pore throats), clay swelling (water sensitivity), emulsion blockage, asphaltene deposition, scale formation, and bacterial growth. The skin factor quantifies formation damage. Skin values greater than 0 indicate damage, while negative skin indicates stimulation. Prevention includes using compatible fluids, clay stabilizers, and proper filtration. Remediation methods include acidizing, hydraulic fracturing, and bypass techniques.",
         "source": "SPE Formation Damage Manual"},
        {"title": "Enhanced Oil Recovery Screening", "category": "Reservoir",
         "content": "EOR screening criteria help identify suitable methods for specific reservoirs. Thermal methods (steam, in-situ combustion) are best for heavy oils (greater than 10 degrees API) with depths less than 3,000 ft and thickness greater than 20 ft. Chemical methods (polymer, surfactant, ASP) suit light to medium oils (20-35 degrees API) with permeability greater than 50 mD. CO2 miscible flooding works for oils with minimum miscibility pressure (MMP) less than fracture pressure. Nitrogen injection suits high-pressure, light oil reservoirs. Screening criteria include oil viscosity, gravity, reservoir depth, temperature, permeability, and formation type. Economic evaluation considers incremental oil price, operating costs, and capital investment.",
         "source": "SPE EOR Screening Manual"},
    ]

    all_docs = drilling_docs + safety_docs + equipment_docs + production_docs + reservoir_docs
    documents.extend(all_docs)
    return documents
